kind = "web"
previewPath = "/"
title = "Darapet Technology"
version = "1.0.0"
id = "artifacts/darapet-website"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25282

[services.development]
run = "pnpm --filter @workspace/darapet-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/darapet-website", "run", "build" ]
serve = "static"
publicDir = "artifacts/darapet-website/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25282"
BASE_PATH = "/"
